import type { BlogArticle } from "@/lib/blog/types";

// Editorial content below is sample/mock copy written to demonstrate the
// blog layout and internal linking structure. Replace with real, reviewed
// articles before launch.

export const ARTICLES: BlogArticle[] = [
  {
    slug: "complete-guide-to-yala-national-park-safari",
    title: "Complete Guide to Yala National Park Safari",
    category: "yala",
    date: "18th September 2026",
    heroImage: "/images/parks/yala.jpg",
    heroAlt: "Misty hills and open grassland in Yala National Park",
    excerpt: "Everything first-time visitors need to know before booking a Yala safari — packages, timing, wildlife and what to expect on the day.",
    internalLinkLabel: "Yala Safari",
    internalLinkHref: "/safaris/yala",
    blocks: [
      { type: "paragraph", text: "Yala National Park is Sri Lanka's most celebrated wildlife destination, and for good reason — it's home to one of the highest densities of leopards anywhere in the world, alongside elephants, sloth bears, crocodiles and a huge variety of birdlife. If you're planning your first safari here, this guide covers everything from choosing a package to knowing what to expect once you're through the gates." },
      { type: "image", src: "/images/scenic/safari-jeeps.jpg", alt: "A line of 4x4 safari jeeps ready for a game drive", caption: "Open-sided 4x4 jeeps are the standard way to explore Yala." },
      { type: "heading", text: "Choosing Your Safari" },
      { type: "paragraph", text: "Yala safaris typically run as Half-Day, 7-Hour or Full-Day drives, in either a private jeep or a shared vehicle. Private tours give you full control over pace and stops, while shared safaris are a more budget-friendly way to experience the same park. Full-day safaris cover the most ground and give you the best chance of a varied sightlist." },
      { type: "heading", text: "What to Expect on the Day" },
      { type: "paragraph", text: "Most safaris begin very early — around 5:00 AM — since wildlife tends to be most active before the heat of the day sets in. Your guide will know the park's trails, waterholes and recent sighting reports, weaving between them as the morning unfolds. Expect dust, bumpy roads and long stretches of quiet scanning between the exciting moments." },
      { type: "quote", text: "The best Yala mornings aren't the busiest ones — they're the ones where your guide knows exactly where to wait." },
      { type: "paragraph", text: "Ready to plan your own trip? Compare our Half-Day, 7-Hour and Full-Day Yala packages and book online with a live, itemised total before you pay." },
    ],
  },
  {
    slug: "best-time-to-visit-yala-national-park",
    title: "Best Time to Visit Yala National Park",
    category: "yala",
    date: "15th September 2026",
    heroImage: "/images/wildlife/spotted-deer.jpg",
    heroAlt: "A spotted deer grazing in open grassland",
    excerpt: "From dry-season leopard activity to early-morning light for photography, here's how to time your Yala safari.",
    internalLinkLabel: "Yala Safari",
    internalLinkHref: "/safaris/yala",
    blocks: [
      { type: "paragraph", text: "Timing matters in Yala — both the time of year and the time of day change what you're likely to see. Here's how to think about both when planning your trip." },
      { type: "heading", text: "Time of Year" },
      { type: "paragraph", text: "The dry season, roughly February through July, is generally considered the strongest period for wildlife viewing. As waterholes shrink, animals concentrate around the remaining water sources, making sightings more predictable. The wetter months bring lush green scenery and fewer crowds, but wildlife can be more dispersed across the park." },
      { type: "image", src: "/images/parks/yala.jpg", alt: "Open grassland and forest in Yala National Park", caption: "Yala's landscape shifts dramatically between wet and dry seasons." },
      { type: "heading", text: "Time of Day" },
      { type: "paragraph", text: "Early morning and late afternoon are consistently the most active periods, as temperatures are cooler and animals move more. A morning safari also gives you the softest light for photography, while afternoon drives can end with a memorable sunset over the grassland." },
      { type: "paragraph", text: "Whichever season you visit, a Half-Day, 7-Hour or Full-Day safari with an experienced local driver is the best way to make the most of your window in the park." },
    ],
  },
  {
    slug: "yala-vs-udawalawe-vs-bundala-which-safari-should-you-choose",
    title: "Yala vs Udawalawe vs Bundala: Which Safari Should You Choose?",
    category: "planning",
    date: "12th September 2026",
    heroImage: "/images/parks/udawalawe.jpg",
    heroAlt: "Open grassland and reservoir views in Udawalawe National Park",
    excerpt: "Three parks, three very different safari experiences. Here's how to decide which one fits your trip.",
    internalLinkLabel: "Safari Parks Overview",
    internalLinkHref: "/safaris",
    blocks: [
      { type: "paragraph", text: "Sri Lanka's southern safari circuit offers several excellent parks, each with its own character. If you're only visiting one or two, here's how Yala, Udawalawe and Bundala compare." },
      { type: "heading", text: "Yala — Best for Leopards" },
      { type: "paragraph", text: "Yala is the headline destination for a reason: it has one of the highest leopard densities in the world, plus elephants, sloth bears and crocodiles. It's also the busiest of the three, especially in peak season, so expect more jeep traffic on popular routes." },
      { type: "image", src: "/images/parks/bundala.jpg", alt: "Wetlands and lagoons in Bundala National Park", caption: "Bundala's wetlands offer a quieter, bird-focused alternative." },
      { type: "heading", text: "Udawalawe — Best for Elephants" },
      { type: "paragraph", text: "Udawalawe's open grassland and reservoir make elephant herds easy to spot on almost every drive. It's a great option for families and first-time safari visitors who want reliable sightings without the density of Yala's jeep traffic." },
      { type: "heading", text: "Bundala — Best for Birdwatching" },
      { type: "paragraph", text: "A Ramsar-listed wetland reserve, Bundala is the pick for birdwatchers and photographers who want a quieter, slower-paced safari alongside migratory waterbirds, crocodiles and the occasional elephant." },
      { type: "paragraph", text: "Not sure which is right for you? Browse all our safari parks side by side and compare packages before you book." },
    ],
  },
  {
    slug: "half-day-vs-7-hour-vs-full-day-yala-safari",
    title: "Half-Day vs 7-Hour vs Full-Day Yala Safari",
    category: "yala",
    date: "10th September 2026",
    heroImage: "/images/scenic/guide-jeep.jpg",
    heroAlt: "A safari guide beside jeeps parked on a dirt track in Yala National Park",
    excerpt: "A practical comparison of Yala's three safari durations, so you can pick the right one for your schedule and budget.",
    internalLinkLabel: "Yala Safari",
    internalLinkHref: "/safaris/yala",
    blocks: [
      { type: "paragraph", text: "One of the first decisions you'll make when booking a Yala safari is how long to spend in the park. Here's what each option actually gets you." },
      { type: "heading", text: "Half-Day Safari" },
      { type: "paragraph", text: "Typically an early-morning drive of around four to five hours, the Half-Day option is ideal if you're short on time or combining the safari with other activities the same day. You'll still cover a good stretch of the park during the most active wildlife hours." },
      { type: "heading", text: "7-Hour Safari" },
      { type: "paragraph", text: "The 7-Hour safari extends your morning well into midday, giving your guide more flexibility to chase sightings, wait at promising waterholes, or explore routes further from the entrance. It's a solid middle ground between time and coverage." },
      { type: "heading", text: "Full-Day Safari" },
      { type: "paragraph", text: "Running from early morning until early evening with a break for lunch, the Full-Day safari covers the most ground and includes both the morning and late-afternoon activity windows — generally your best odds for a varied and memorable sightlist." },
      { type: "paragraph", text: "Compare exact pricing and inclusions for each duration on our Yala safari packages page." },
    ],
  },
  {
    slug: "yala-national-park-entrance-fees-explained",
    title: "Yala National Park Entrance Fees Explained",
    category: "yala",
    date: "8th September 2026",
    heroImage: "/images/scenic/parking.png",
    heroAlt: "Safari jeep convoy in Yala National Park",
    excerpt: "Why the park entrance ticket is usually a separate cost from your safari package, and how to budget for it.",
    internalLinkLabel: "Yala Safari / Booking",
    internalLinkHref: "/safaris/yala",
    blocks: [
      { type: "paragraph", text: "One of the most common questions we get from first-time visitors is why the park entrance ticket isn't automatically bundled into the safari price. Here's a quick explainer." },
      { type: "heading", text: "Who Sets the Price" },
      { type: "paragraph", text: "Entrance fees for Yala and Sri Lanka's other national parks are set by the Department of Wildlife Conservation, not by individual safari operators. Rates can change and vary by park, which is why we show the entrance ticket as its own line item rather than folding it into a fixed package price." },
      { type: "image", src: "/images/parks/yala.jpg", alt: "The entrance road into Yala National Park", caption: "Entrance tickets are issued and priced separately from your jeep and driver." },
      { type: "heading", text: "How It's Handled When You Book" },
      { type: "paragraph", text: "When you book with us, you'll see the entrance ticket clearly listed as an optional add-on or a separate cost, depending on the package you select. That way, the total you see before checkout always reflects exactly what you're paying for." },
      { type: "paragraph", text: "Have questions about a specific package's inclusions? Check the pricing details on the Yala safari page before you book." },
    ],
  },
  {
    slug: "what-to-bring-on-a-sri-lankan-safari",
    title: "What to Bring on a Sri Lankan Safari",
    category: "planning",
    date: "5th September 2026",
    heroImage: "/images/scenic/safari-jeeps.jpg",
    heroAlt: "A line of 4x4 safari jeeps ready for a game drive",
    excerpt: "A practical packing checklist for your first safari drive, from clothing to camera gear.",
    internalLinkLabel: "Safari Parks",
    internalLinkHref: "/safaris",
    blocks: [
      { type: "paragraph", text: "Safari mornings start early and the jeep tracks can be rough, so a little preparation goes a long way. Here's what we recommend packing." },
      { type: "heading", text: "Clothing" },
      { type: "paragraph", text: "Comfortable, neutral-toned clothing and closed shoes work best — think layers, since early mornings can be cool before the sun climbs. A hat and sunglasses will save you from the midday glare once the drive stretches into the afternoon." },
      { type: "heading", text: "Gear" },
      { type: "paragraph", text: "A camera and binoculars are the two most useful things you can bring. Even a basic pair of binoculars dramatically improves distant sightings, and sunscreen is essential given how much time you'll spend exposed to direct sun in an open jeep." },
      { type: "image", src: "/images/wildlife/peacock.jpg", alt: "An Indian peacock displaying its plumage", caption: "A decent zoom lens or binoculars make a big difference for distant sightings." },
      { type: "heading", text: "Other Essentials" },
      { type: "paragraph", text: "Bring your passport or ID, some cash for anything not covered by your package, and drinking water — most of our packages include water, but it's worth checking before you head out." },
      { type: "paragraph", text: "Browse our full range of safari parks and packages to plan the rest of your trip." },
    ],
  },
  {
    slug: "hambantota-port-to-yala-safari-guide",
    title: "Hambantota Port to Yala Safari Guide",
    category: "hambantota",
    date: "2nd September 2026",
    heroImage: "/images/scenic/guide-jeep.jpg",
    heroAlt: "A safari guide beside jeeps parked on a dirt track in Yala National Park",
    excerpt: "A practical guide for cruise passengers looking to fit a Yala safari into a short stop at Hambantota Port.",
    internalLinkLabel: "Hambantota Page",
    internalLinkHref: "/#enquire",
    blocks: [
      { type: "paragraph", text: "If your ship is docking at Hambantota International Cruise Port, a Yala safari is one of the most rewarding ways to spend a short window of time ashore. Here's how the trip typically works." },
      { type: "heading", text: "Getting from the Port to the Park" },
      { type: "paragraph", text: "Yala National Park is a manageable drive from Hambantota Port, making it realistic to fit a safari into a single port call. Pickup is coordinated around your confirmed arrival details, and you're transferred directly to the park in a 4x4 safari jeep." },
      { type: "image", src: "/images/parks/yala.jpg", alt: "Misty hills and open grassland in Yala National Park", caption: "Yala is a practical safari option for cruise passengers with limited time ashore." },
      { type: "heading", text: "What to Plan For" },
      { type: "paragraph", text: "Since your return time is fixed by your ship's schedule, it's worth communicating your required return time clearly when booking. Pickup timing can vary depending on port procedures and traffic, so building in some buffer is a good idea." },
      { type: "paragraph", text: "Interested in this itinerary? Get in touch with your cruise details and we'll help coordinate the timing." },
    ],
  },
  {
    slug: "where-to-see-elephants-in-sri-lanka-udawalawe-guide",
    title: "Where to See Elephants in Sri Lanka: Udawalawe Guide",
    category: "udawalawe",
    date: "29th August 2026",
    heroImage: "/images/parks/udawalawe.jpg",
    heroAlt: "Open grassland and reservoir views in Udawalawe National Park",
    excerpt: "Why Udawalawe is Sri Lanka's most reliable park for elephant sightings, and what to expect on a visit.",
    internalLinkLabel: "Udawalawe Safari",
    internalLinkHref: "/safaris/udawalawe",
    blocks: [
      { type: "paragraph", text: "If seeing wild elephants is top of your list, Udawalawe National Park is widely regarded as Sri Lanka's best option. Its open habitat and large resident elephant population make for some of the most consistent sightings anywhere in the country." },
      { type: "heading", text: "Why Udawalawe Works So Well for Elephants" },
      { type: "paragraph", text: "Unlike Yala's mixed forest and scrub, much of Udawalawe is open grassland surrounding a large reservoir. That openness means elephants are far easier to spot at a distance, and herds often gather near the water in full view of the safari track." },
      { type: "image", src: "/images/parks/udawalawe.jpg", alt: "Elephants gathering near the Udawalawe reservoir", caption: "Herds regularly gather around the reservoir's edge." },
      { type: "heading", text: "Beyond Elephants" },
      { type: "paragraph", text: "While elephants are the star attraction, keep an eye out for water buffalo, deer, crocodiles, monkeys and a good variety of birdlife across the park's grassland and scrub habitats." },
      { type: "paragraph", text: "Ready to plan your visit? Compare our Udawalawe safari packages and durations." },
    ],
  },
  {
    slug: "bundala-national-park-bird-watching-guide",
    title: "Bundala National Park Bird Watching Guide",
    category: "bundala",
    date: "26th August 2026",
    heroImage: "/images/parks/bundala.jpg",
    heroAlt: "Wetlands and lagoons in Bundala National Park",
    excerpt: "A guide to one of Sri Lanka's most important wetland reserves and its migratory birdlife.",
    internalLinkLabel: "Bundala Safari",
    internalLinkHref: "/safaris/bundala",
    blocks: [
      { type: "paragraph", text: "Bundala National Park is an internationally recognised wetland reserve — a Ramsar site — and one of the best birdwatching destinations in Sri Lanka. If Yala's crowds aren't for you, Bundala offers a quieter, slower-paced alternative built around lagoons and coastal habitat." },
      { type: "heading", text: "What You Might See" },
      { type: "paragraph", text: "Depending on the season, Bundala's lagoons and salt pans can host flamingos and other migratory waterbirds, alongside resident species like painted storks, herons and egrets. Crocodiles and occasional elephants also pass through the park." },
      { type: "image", src: "/images/wildlife/crocodile.jpg", alt: "A mugger crocodile resting at the water's edge", caption: "Crocodiles are a common sight along Bundala's lagoons." },
      { type: "heading", text: "Best Time for Birding" },
      { type: "paragraph", text: "Bird activity varies with season, water levels and migration cycles, so no specific sighting can ever be guaranteed — but early morning and late afternoon tend to be the most active windows for photography and viewing." },
      { type: "paragraph", text: "Explore our Bundala safari packages to plan a visit around your travel dates." },
    ],
  },
  {
    slug: "wildlife-you-can-see-in-yala-national-park",
    title: "Wildlife You Can See in Yala National Park",
    category: "wildlife",
    date: "23rd August 2026",
    heroImage: "/images/wildlife/sloth-bear.jpg",
    heroAlt: "A sloth bear foraging in the Sri Lankan dry-zone forest",
    excerpt: "Beyond leopards — the full range of wildlife you might encounter on a Yala safari.",
    internalLinkLabel: "Yala Safari",
    internalLinkHref: "/safaris/yala",
    blocks: [
      { type: "paragraph", text: "Yala's leopards get most of the attention, but the park is home to a genuinely diverse range of wildlife across its forest, grassland, lagoon and coastal habitats. Here's a look at what else you might spot." },
      { type: "heading", text: "Large Mammals" },
      { type: "paragraph", text: "Asian elephants are a common sight, particularly near waterholes, while sloth bears — shy and less frequently seen — are a genuine highlight when they do appear. Wild boar and spotted deer are among the most reliably spotted species." },
      { type: "image", src: "/images/wildlife/wild-boar.jpg", alt: "A wild boar in the Sri Lankan dry-zone forest", caption: "Wild boar are among the more frequently spotted mammals in Yala." },
      { type: "heading", text: "Reptiles and Birds" },
      { type: "paragraph", text: "Crocodiles bask along Yala's waterways and lagoons, while the park's birdlife ranges from peacocks displaying in open clearings to a long list of resident and migratory species drawn to its wetland areas." },
      { type: "paragraph", text: "As always, wildlife sightings are never guaranteed — but Yala's density and diversity give you an excellent chance across a full day in the park. Browse our Yala safari packages to start planning." },
    ],
  },
  {
    slug: "yala-safari-with-children-family-guide",
    title: "Yala Safari with Children: Family Guide",
    category: "family",
    date: "20th August 2026",
    heroImage: "/images/wildlife/spotted-deer.jpg",
    heroAlt: "A spotted deer grazing in open grassland",
    excerpt: "What families should know before bringing children on a Yala safari, from timing to comfort.",
    internalLinkLabel: "Yala Safari",
    internalLinkHref: "/safaris/yala",
    blocks: [
      { type: "paragraph", text: "A safari can be an unforgettable experience for kids, but a few practical considerations make the day smoother for the whole family." },
      { type: "heading", text: "Choosing the Right Duration" },
      { type: "paragraph", text: "For younger children, a Half-Day safari is often the most manageable option — long enough for a real safari experience without pushing bedtime routines or attention spans too far. Older children and teens tend to enjoy the longer 7-Hour or Full-Day drives just as much as adults do." },
      { type: "heading", text: "What to Prepare For" },
      { type: "paragraph", text: "Early starts and rough roads are part of the experience, so pack accordingly — sun protection, snacks, and comfortable clothing all help. We recommend parents use their own judgement for very young children given the early pickup time and bumpy tracks." },
      { type: "image", src: "/images/wildlife/peacock.jpg", alt: "An Indian peacock displaying its plumage", caption: "Colourful, easy-to-spot species like peacocks are often a hit with younger travellers." },
      { type: "heading", text: "Making It Memorable" },
      { type: "paragraph", text: "Bringing along binoculars for the kids and letting them help \"spot\" wildlife tends to keep the whole family engaged, even during the quieter stretches between sightings." },
      { type: "paragraph", text: "Ready to book a family-friendly Yala safari? Explore our packages and passenger options." },
    ],
  },
  {
    slug: "safari-photography-tips-for-yala",
    title: "Safari Photography Tips for Yala",
    category: "photography",
    date: "17th August 2026",
    heroImage: "/images/wildlife/peacock.jpg",
    heroAlt: "An Indian peacock displaying its plumage",
    excerpt: "Practical advice for getting better wildlife photos on your Yala safari, without disturbing the animals.",
    internalLinkLabel: "Yala Safari",
    internalLinkHref: "/safaris/yala",
    blocks: [
      { type: "paragraph", text: "Yala's open-sided jeeps and golden early-morning light make it a genuinely rewarding park for photography — but a little preparation and etiquette go a long way toward better shots and a better experience for everyone." },
      { type: "heading", text: "Gear" },
      { type: "paragraph", text: "A telephoto lens or a good pair of binoculars makes the biggest difference, since most sightings happen at a distance. If you're shooting on a phone, a small clip-on zoom lens can help, though it won't match a dedicated camera for distant subjects." },
      { type: "image", src: "/images/wildlife/sloth-bear.jpg", alt: "A sloth bear foraging in the Sri Lankan dry-zone forest", caption: "Patience and a longer lens pay off for shyer species like sloth bears." },
      { type: "heading", text: "Etiquette" },
      { type: "paragraph", text: "Keep noise to a minimum, follow your driver's instructions on positioning, and never encourage or bait wildlife for a better shot. The best photos come from patience, not proximity." },
      { type: "heading", text: "Light and Timing" },
      { type: "paragraph", text: "Early morning and late afternoon offer the softest, most flattering light — another good reason to book a Half-Day or Full-Day safari that covers those windows." },
      { type: "paragraph", text: "Plan your shoot around the right package on our Yala safari page." },
    ],
  },
  {
    slug: "how-to-get-to-yala-from-ella-mirissa-and-hambantota",
    title: "How to Get to Yala from Ella, Mirissa and Hambantota",
    category: "transport",
    date: "14th August 2026",
    heroImage: "/images/scenic/safari-jeeps.jpg",
    heroAlt: "A line of 4x4 safari jeeps ready for a game drive",
    excerpt: "Travel times and transport options for reaching Yala from three of southern Sri Lanka's most popular bases.",
    internalLinkLabel: "Taxi & Car Rental",
    internalLinkHref: "/#enquire",
    blocks: [
      { type: "paragraph", text: "Yala is a popular add-on to a southern Sri Lanka itinerary, and getting there from nearby towns is generally straightforward with a private driver. Here's what to expect from three common starting points." },
      { type: "heading", text: "From Ella" },
      { type: "paragraph", text: "Ella sits in the hill country, so the drive down to Yala takes you through winding mountain roads before opening onto the flatter, drier south. It's a scenic but longer journey — worth planning as its own travel day rather than squeezing in alongside a safari." },
      { type: "heading", text: "From Mirissa" },
      { type: "paragraph", text: "Coming from the south coast, Mirissa to Yala is a more direct coastal-and-inland route, making it a popular pairing for travellers combining beach time with a safari." },
      { type: "image", src: "/images/scenic/guide-jeep.jpg", alt: "A safari guide beside jeeps parked on a dirt track in Yala National Park", caption: "A private driver takes the guesswork out of connecting these stops." },
      { type: "heading", text: "From Hambantota" },
      { type: "paragraph", text: "Hambantota, including cruise arrivals at the port, is the closest of the three to Yala, making a safari a realistic option even on a tight schedule." },
      { type: "paragraph", text: "Need a private transfer or full car rental for your trip? Get in touch and we'll help plan the route." },
    ],
  },
  {
    slug: "morning-vs-evening-safari-in-yala",
    title: "Morning vs Evening Safari in Yala",
    category: "yala",
    date: "11th August 2026",
    heroImage: "/images/parks/yala.jpg",
    heroAlt: "Misty hills and open grassland in Yala National Park",
    excerpt: "How wildlife activity, light and crowds differ between a morning and an evening drive in Yala.",
    internalLinkLabel: "Yala Safari",
    internalLinkHref: "/safaris/yala",
    blocks: [
      { type: "paragraph", text: "Most Yala safaris run in the early morning, but afternoon and evening drives are also available depending on your package. Here's how the two compare." },
      { type: "heading", text: "Morning Safaris" },
      { type: "paragraph", text: "Starting around 5:00 AM, morning drives catch animals at their most active after the cool overnight hours, with soft light that's ideal for photography. It's also the busiest time slot, so popular routes can see more jeep traffic." },
      { type: "heading", text: "Evening Safaris" },
      { type: "paragraph", text: "As temperatures drop again in the late afternoon, wildlife activity picks up once more. Evening drives often end with a striking sunset over the grassland, and can feel slightly less crowded than the morning rush." },
      { type: "image", src: "/images/parks/yala.jpg", alt: "Sunset light over grassland in Yala National Park", caption: "Late-afternoon light can be just as rewarding as an early start." },
      { type: "paragraph", text: "A Full-Day safari lets you experience both windows in a single visit. See our Yala packages for exact timing." },
    ],
  },
  {
    slug: "leopard-spotting-in-yala-what-travelers-should-know",
    title: "Leopard Spotting in Yala: What Travelers Should Know",
    category: "wildlife",
    date: "8th August 2026",
    heroImage: "/images/parks/yala.jpg",
    heroAlt: "Misty hills and open grassland in Yala National Park",
    excerpt: "Realistic expectations, good etiquette and what actually improves your odds of a leopard sighting in Yala.",
    internalLinkLabel: "Yala Safari",
    internalLinkHref: "/safaris/yala",
    blocks: [
      { type: "paragraph", text: "Yala's leopard population is one of the densest in the world, which is why so many visitors come specifically hoping for a sighting. Here's what's worth knowing before your safari." },
      { type: "heading", text: "Sightings Are Never Guaranteed" },
      { type: "paragraph", text: "No matter how experienced your guide is, leopards are wild animals moving freely through their own territory. A high density of leopards means a good chance of a sighting over a full day in the park, but never a certainty." },
      { type: "heading", text: "What Actually Helps" },
      { type: "paragraph", text: "An experienced local driver who knows the park's trails, recent sighting reports and favourite resting spots makes a real difference. A longer safari — 7-Hour or Full-Day — also gives you more time in the park and more chances across both morning and afternoon activity windows." },
      { type: "image", src: "/images/parks/yala.jpg", alt: "Dense forest and rocky outcrops in Yala National Park", caption: "Leopards often rest on rocky outcrops and low branches during the heat of the day." },
      { type: "heading", text: "Sighting Etiquette" },
      { type: "paragraph", text: "If a leopard is spotted, keep noise down, follow your driver's positioning, and give other jeeps room to view respectfully. A calm, patient approach benefits both the animal and everyone hoping for a clear look." },
      { type: "paragraph", text: "Plan your own leopard-focused safari on our Yala packages page." },
    ],
  },
];

export function getArticle(slug: string): BlogArticle | undefined {
  return ARTICLES.find((article) => article.slug === slug);
}

export function getArticleSlugs(): string[] {
  return ARTICLES.map((article) => article.slug);
}

export function getLatestArticles(count: number): BlogArticle[] {
  return ARTICLES.slice(0, count);
}
